:'
#lr 0.005
#finetune birds 4
python3 main_incremental.py --exp_name design6_finetune_lr0005_bs32 --datasets birds --num_tasks 4 --network disentangle --disentangle_design design6 --heads_architecture design6 --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_birds_new/ --lr 0.005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach finetune --gpu=0 &
python3 main_incremental.py --exp_name design7_finetune_lr0005_bs32 --datasets birds --num_tasks 4 --network disentangle --disentangle_design design7 --heads_architecture design7 --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_birds_new/ --lr 0.005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach finetune --gpu=1 &
python3 main_incremental.py --exp_name design2_finetune_lr0005_bs32 --datasets birds --num_tasks 4 --network disentangle --disentangle_design design2 --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_birds_new/ --lr 0.005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach finetune --gpu=2 &
python3 main_incremental.py --exp_name shapeonly_new_finetune_lr0005_bs32 --datasets birds --num_tasks 4 --network disentangle --disentangle_design shapeonly --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_birds_new/ --lr 0.005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach finetune --gpu=2 &
python3 main_incremental.py --exp_name coloronly_new_finetune_lr0005_bs32 --datasets birds --num_tasks 4 --network disentangle --disentangle_design coloronly --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_birds_new/ --lr 0.005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach finetune --gpu=1 ;

#lwf birds 4
python3 main_incremental.py --exp_name design6_lwf_lr0005_bs32 --datasets birds --num_tasks 4 --network disentangle --disentangle_design design6 --heads_architecture design6 --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_birds_new/ --lr 0.005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach lwf --lamb 1 --T 2 --gpu=0 &
python3 main_incremental.py --exp_name design7_lwf_lr0005_bs32 --datasets birds --num_tasks 4 --network disentangle --disentangle_design design7 --heads_architecture design7 --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_birds_new/ --lr 0.005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach lwf --lamb 1 --T 2 --gpu=1 &
python3 main_incremental.py --exp_name design2_lwf_lr0005_bs32 --datasets birds --num_tasks 4 --network disentangle --disentangle_design design2 --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_birds_new/ --lr 0.005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach lwf --lamb 1 --T 2 --gpu=2 &
python3 main_incremental.py --exp_name shapeonly_new_lwf_lr0005_bs32 --datasets birds --num_tasks 4 --network disentangle --disentangle_design shapeonly --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_birds_new/ --lr 0.005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach lwf --lamb 1 --T 2 --gpu=2 &
python3 main_incremental.py --exp_name coloronly_new_lwf_lr0005_bs32 --datasets birds --num_tasks 4 --network disentangle --disentangle_design coloronly --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_birds_new/ --lr 0.005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach lwf --lamb 1 --T 2 --gpu=1 ;


#ewc birds 4
python3 main_incremental.py --exp_name design6_ewc5000_lr0005_bs32 --datasets birds --num_tasks 4 --network disentangle --disentangle_design design6 --heads_architecture design6 --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_birds_new/ --lr 0.005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach ewc --lamb 5000 --sampling_type max_pred --num_samples -1 --gpu=0 &
python3 main_incremental.py --exp_name design7_ewc5000_lr0005_bs32 --datasets birds --num_tasks 4 --network disentangle --disentangle_design design7 --heads_architecture design7 --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_birds_new/ --lr 0.005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach ewc --lamb 5000 --sampling_type max_pred --num_samples -1 --gpu=1 &
python3 main_incremental.py --exp_name design2_ewc5000_lr0005_bs32 --datasets birds --num_tasks 4 --network disentangle --disentangle_design design2 --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_birds_new/ --lr 0.005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach ewc --lamb 5000 --sampling_type max_pred --num_samples -1 --gpu=2 &
python3 main_incremental.py --exp_name shapeonly_new_ewc5000_lr0005_bs32 --datasets birds --num_tasks 4 --network disentangle --disentangle_design shapeonly --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_birds_new/ --lr 0.005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach ewc --lamb 5000 --sampling_type max_pred --num_samples -1 --gpu=2 &
python3 main_incremental.py --exp_name coloronly_new_ewc5000_lr0005_bs32 --datasets birds --num_tasks 4 --network disentangle --disentangle_design coloronly --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_birds_new/ --lr 0.005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach ewc --lamb 5000 --sampling_type max_pred --num_samples -1 --gpu=1 ;


#finetune flowers 4
python3 main_incremental.py --exp_name design6_finetune_lr0005_bs32 --datasets flowers --num_tasks 4 --network disentangle --disentangle_design design6 --heads_architecture design6 --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_flowers_new_new/ --lr 0.005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach finetune --gpu=0 &
python3 main_incremental.py --exp_name design7_finetune_lr0005_bs32 --datasets flowers --num_tasks 4 --network disentangle --disentangle_design design7 --heads_architecture design7 --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_flowers_new_new/ --lr 0.005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach finetune --gpu=1 &
python3 main_incremental.py --exp_name design2_finetune_lr0005_bs32 --datasets flowers --num_tasks 4 --network disentangle --disentangle_design design2 --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_flowers_new_new/ --lr 0.005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach finetune --gpu=2 &
python3 main_incremental.py --exp_name shapeonly_new_finetune_lr0005_bs32 --datasets flowers --num_tasks 4 --network disentangle --disentangle_design shapeonly --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_flowers_new_new/ --lr 0.005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach finetune --gpu=2 &
python3 main_incremental.py --exp_name coloronly_new_finetune_lr0005_bs32 --datasets flowers --num_tasks 4 --network disentangle --disentangle_design coloronly --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_flowers_new_new/ --lr 0.005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach finetune --gpu=1 ;

#lwf flowers 4
python3 main_incremental.py --exp_name design6_lwf_lr0005_bs32 --datasets flowers --num_tasks 4 --network disentangle --disentangle_design design6 --heads_architecture design6 --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_flowers_new_new/ --lr 0.005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach lwf --lamb 1 --T 2 --gpu=0 &
python3 main_incremental.py --exp_name design7_lwf_lr0005_bs32 --datasets flowers --num_tasks 4 --network disentangle --disentangle_design design7 --heads_architecture design7 --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_flowers_new_new/ --lr 0.005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach lwf --lamb 1 --T 2 --gpu=1 &
python3 main_incremental.py --exp_name design2_lwf_lr0005_bs32 --datasets flowers --num_tasks 4 --network disentangle --disentangle_design design2 --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_flowers_new_new/ --lr 0.005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach lwf --lamb 1 --T 2 --gpu=2 &
python3 main_incremental.py --exp_name shapeonly_new_lwf_lr0005_bs32 --datasets flowers --num_tasks 4 --network disentangle --disentangle_design shapeonly --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_flowers_new_new/ --lr 0.005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach lwf --lamb 1 --T 2 --gpu=2 &
python3 main_incremental.py --exp_name coloronly_new_lwf_lr0005_bs32 --datasets flowers --num_tasks 4 --network disentangle --disentangle_design coloronly --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_flowers_new_new/ --lr 0.005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach lwf --lamb 1 --T 2 --gpu=1 ;


#ewc flowers 4
python3 main_incremental.py --exp_name design6_ewc5000_lr0005_bs32 --datasets flowers --num_tasks 4 --network disentangle --disentangle_design design6 --heads_architecture design6 --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_flowers_new_new/ --lr 0.005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach ewc --lamb 5000 --sampling_type max_pred --num_samples -1 --gpu=0 &
python3 main_incremental.py --exp_name design7_ewc5000_lr0005_bs32 --datasets flowers --num_tasks 4 --network disentangle --disentangle_design design7 --heads_architecture design7 --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_flowers_new_new/ --lr 0.005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach ewc --lamb 5000 --sampling_type max_pred --num_samples -1 --gpu=1 &
python3 main_incremental.py --exp_name design2_ewc5000_lr0005_bs32 --datasets flowers --num_tasks 4 --network disentangle --disentangle_design design2 --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_flowers_new_new/ --lr 0.005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach ewc --lamb 5000 --sampling_type max_pred --num_samples -1 --gpu=2 &
python3 main_incremental.py --exp_name shapeonly_new_ewc5000_lr0005_bs32 --datasets flowers --num_tasks 4 --network disentangle --disentangle_design shapeonly --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_flowers_new_new/ --lr 0.005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach ewc --lamb 5000 --sampling_type max_pred --num_samples -1 --gpu=2 &
python3 main_incremental.py --exp_name coloronly_new_ewc5000_lr0005_bs32 --datasets flowers --num_tasks 4 --network disentangle --disentangle_design coloronly --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_flowers_new_new/ --lr 0.005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach ewc --lamb 5000 --sampling_type max_pred --num_samples -1 --gpu=1 ;
#lr 0.0005

#finetune birds 4
python3 main_incremental.py --exp_name design6_finetune_lr00005_bs32 --datasets birds --num_tasks 4 --network disentangle --disentangle_design design6 --heads_architecture design6 --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_birds_new/ --lr 0.0005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach finetune --gpu=0 &
python3 main_incremental.py --exp_name design7_finetune_lr00005_bs32 --datasets birds --num_tasks 4 --network disentangle --disentangle_design design7 --heads_architecture design7 --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_birds_new/ --lr 0.0005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach finetune --gpu=1 &
python3 main_incremental.py --exp_name design2_finetune_lr00005_bs32 --datasets birds --num_tasks 4 --network disentangle --disentangle_design design2 --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_birds_new/ --lr 0.0005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach finetune --gpu=2 &
python3 main_incremental.py --exp_name shapeonly_new_finetune_lr00005_bs32 --datasets birds --num_tasks 4 --network disentangle --disentangle_design shapeonly --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_birds_new/ --lr 0.0005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach finetune --gpu=2 &
python3 main_incremental.py --exp_name coloronly_new_finetune_lr00005_bs32 --datasets birds --num_tasks 4 --network disentangle --disentangle_design coloronly --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_birds_new/ --lr 0.0005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach finetune --gpu=1 ;

#lwf birds 4
python3 main_incremental.py --exp_name design6_lwf_lr00005_bs32 --datasets birds --num_tasks 4 --network disentangle --disentangle_design design6 --heads_architecture design6 --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_birds_new/ --lr 0.0005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach lwf --lamb 1 --T 2 --gpu=0 &
python3 main_incremental.py --exp_name design7_lwf_lr00005_bs32 --datasets birds --num_tasks 4 --network disentangle --disentangle_design design7 --heads_architecture design7 --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_birds_new/ --lr 0.0005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach lwf --lamb 1 --T 2 --gpu=1 &
python3 main_incremental.py --exp_name design2_lwf_lr00005_bs32 --datasets birds --num_tasks 4 --network disentangle --disentangle_design design2 --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_birds_new/ --lr 0.0005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach lwf --lamb 1 --T 2 --gpu=2 &
python3 main_incremental.py --exp_name shapeonly_new_lwf_lr00005_bs32 --datasets birds --num_tasks 4 --network disentangle --disentangle_design shapeonly --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_birds_new/ --lr 0.0005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach lwf --lamb 1 --T 2 --gpu=2 &
python3 main_incremental.py --exp_name coloronly_new_lwf_lr00005_bs32 --datasets birds --num_tasks 4 --network disentangle --disentangle_design coloronly --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_birds_new/ --lr 0.0005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach lwf --lamb 1 --T 2 --gpu=1 ;


#ewc birds 4
python3 main_incremental.py --exp_name design6_ewc5000_lr00005_bs32 --datasets birds --num_tasks 4 --network disentangle --disentangle_design design6 --heads_architecture design6 --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_birds_new/ --lr 0.0005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach ewc --lamb 5000 --sampling_type max_pred --num_samples -1 --gpu=0 &
python3 main_incremental.py --exp_name design7_ewc5000_lr00005_bs32 --datasets birds --num_tasks 4 --network disentangle --disentangle_design design7 --heads_architecture design7 --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_birds_new/ --lr 0.0005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach ewc --lamb 5000 --sampling_type max_pred --num_samples -1 --gpu=1 &
python3 main_incremental.py --exp_name design2_ewc5000_lr00005_bs32 --datasets birds --num_tasks 4 --network disentangle --disentangle_design design2 --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_birds_new/ --lr 0.0005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach ewc --lamb 5000 --sampling_type max_pred --num_samples -1 --gpu=2 &
python3 main_incremental.py --exp_name shapeonly_new_ewc5000_lr00005_bs32 --datasets birds --num_tasks 4 --network disentangle --disentangle_design shapeonly --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_birds_new/ --lr 0.0005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach ewc --lamb 5000 --sampling_type max_pred --num_samples -1 --gpu=2 &
python3 main_incremental.py --exp_name coloronly_new_ewc5000_lr00005_bs32 --datasets birds --num_tasks 4 --network disentangle --disentangle_design coloronly --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_birds_new/ --lr 0.0005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach ewc --lamb 5000 --sampling_type max_pred --num_samples -1 --gpu=1 ;


#finetune flowers 4
python3 main_incremental.py --exp_name design6_finetune_lr00005_bs32 --datasets flowers --num_tasks 4 --network disentangle --disentangle_design design6 --heads_architecture design6 --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_flowers_new_new/ --lr 0.0005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach finetune --gpu=0 &
python3 main_incremental.py --exp_name design7_finetune_lr00005_bs32 --datasets flowers --num_tasks 4 --network disentangle --disentangle_design design7 --heads_architecture design7 --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_flowers_new_new/ --lr 0.0005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach finetune --gpu=1 &
python3 main_incremental.py --exp_name design2_finetune_lr00005_bs32 --datasets flowers --num_tasks 4 --network disentangle --disentangle_design design2 --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_flowers_new_new/ --lr 0.0005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach finetune --gpu=2 &
python3 main_incremental.py --exp_name shapeonly_new_finetune_lr00005_bs32 --datasets flowers --num_tasks 4 --network disentangle --disentangle_design shapeonly --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_flowers_new_new/ --lr 0.0005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach finetune --gpu=2 &
python3 main_incremental.py --exp_name coloronly_new_finetune_lr00005_bs32 --datasets flowers --num_tasks 4 --network disentangle --disentangle_design coloronly --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_flowers_new_new/ --lr 0.0005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach finetune --gpu=1 ;

#lwf flowers 4
python3 main_incremental.py --exp_name design6_lwf_lr00005_bs32 --datasets flowers --num_tasks 4 --network disentangle --disentangle_design design6 --heads_architecture design6 --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_flowers_new_new/ --lr 0.0005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach lwf --lamb 1 --T 2 --gpu=0 &
python3 main_incremental.py --exp_name design7_lwf_lr00005_bs32 --datasets flowers --num_tasks 4 --network disentangle --disentangle_design design7 --heads_architecture design7 --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_flowers_new_new/ --lr 0.0005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach lwf --lamb 1 --T 2 --gpu=1 &
python3 main_incremental.py --exp_name design2_lwf_lr00005_bs32 --datasets flowers --num_tasks 4 --network disentangle --disentangle_design design2 --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_flowers_new_new/ --lr 0.0005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach lwf --lamb 1 --T 2 --gpu=2 &
python3 main_incremental.py --exp_name shapeonly_new_lwf_lr00005_bs32 --datasets flowers --num_tasks 4 --network disentangle --disentangle_design shapeonly --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_flowers_new_new/ --lr 0.0005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach lwf --lamb 1 --T 2 --gpu=2 &
python3 main_incremental.py --exp_name coloronly_new_lwf_lr00005_bs32 --datasets flowers --num_tasks 4 --network disentangle --disentangle_design coloronly --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_flowers_new_new/ --lr 0.0005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach lwf --lamb 1 --T 2 --gpu=1 ;


#ewc flowers 4
python3 main_incremental.py --exp_name design6_ewc5000_lr00005_bs32 --datasets flowers --num_tasks 4 --network disentangle --disentangle_design design6 --heads_architecture design6 --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_flowers_new_new/ --lr 0.0005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach ewc --lamb 5000 --sampling_type max_pred --num_samples -1 --gpu=0 &
python3 main_incremental.py --exp_name design7_ewc5000_lr00005_bs32 --datasets flowers --num_tasks 4 --network disentangle --disentangle_design design7 --heads_architecture design7 --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_flowers_new_new/ --lr 0.0005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach ewc --lamb 5000 --sampling_type max_pred --num_samples -1 --gpu=1 &
python3 main_incremental.py --exp_name design2_ewc5000_lr00005_bs32 --datasets flowers --num_tasks 4 --network disentangle --disentangle_design design2 --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_flowers_new_new/ --lr 0.0005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach ewc --lamb 5000 --sampling_type max_pred --num_samples -1 --gpu=2 &
python3 main_incremental.py --exp_name shapeonly_new_ewc5000_lr00005_bs32 --datasets flowers --num_tasks 4 --network disentangle --disentangle_design shapeonly --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_flowers_new_new/ --lr 0.0005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach ewc --lamb 5000 --sampling_type max_pred --num_samples -1 --gpu=2 &
python3 main_incremental.py --exp_name coloronly_new_ewc5000_lr00005_bs32 --datasets flowers --num_tasks 4 --network disentangle --disentangle_design coloronly --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_flowers_new_new/ --lr 0.0005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach ewc --lamb 5000 --sampling_type max_pred --num_samples -1 --gpu=1 ;


python3 main_incremental.py --exp_name design2_finetune_lr005_bs32 --datasets flowers --num_tasks 4 --network disentangle --disentangle_design design2 --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_flowers_new_new/ --lr 0.05 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach finetune --gpu=0 &
python3 main_incremental.py --exp_name design2_finetune_lr0005_bs32 --datasets flowers --num_tasks 4 --network disentangle --disentangle_design design2 --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_flowers_new_new/ --lr 0.005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach finetune --gpu=1 &
python3 main_incremental.py --exp_name design6_finetune_lr0005_bs32 --datasets flowers --num_tasks 4 --network disentangle --disentangle_design design6 --heads_architecture design6 --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_flowers_new_new/ --lr 0.005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach finetune --gpu=2;
python3 main_incremental.py --exp_name design6_finetune_lr00005_bs32 --datasets flowers --num_tasks 4 --network disentangle --disentangle_design design6 --heads_architecture design6 --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_flowers_new_new/ --lr 0.0005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach finetune --gpu=0 &
python3 main_incremental.py --exp_name design7_finetune_lr0005_bs32 --datasets flowers --num_tasks 4 --network disentangle --disentangle_design design7 --heads_architecture design7 --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_flowers_new_new/ --lr 0.005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach finetune --gpu=1 &
python3 main_incremental.py --exp_name design7_finetune_lr005_bs32 --datasets flowers --num_tasks 4 --network disentangle --disentangle_design design7 --heads_architecture design7 --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_flowers_new_new/ --lr 0.05 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach finetune --gpu=2 ;


python3 main_incremental.py --exp_name design2_lwf_lr005_bs32 --datasets birds --num_tasks 4 --network disentangle --disentangle_design design2 --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_birds_new/ --lr 0.05 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach lwf --lamb 1 --T 2 --gpu=0 &
python3 main_incremental.py --exp_name design2_lwf_lr0005_bs32 --datasets birds --num_tasks 4 --network disentangle --disentangle_design design2 --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_birds_new/ --lr 0.005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach lwf --lamb 1 --T 2 --gpu=1 &
python3 main_incremental.py --exp_name design6_ewc5000_lr005_bs32 --datasets birds --num_tasks 4 --network disentangle --disentangle_design design6 --heads_architecture design6 --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_birds_new/ --lr 0.05 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach ewc --lamb 5000 --sampling_type max_pred --num_samples -1 --gpu=2;
python3 main_incremental.py --exp_name design7_lwf_lr005_bs32 --datasets birds --num_tasks 4 --network disentangle --disentangle_design design7 --heads_architecture design7 --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_birds_new/ --lr 0.05 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach lwf --lamb 1 --T 2 --gpu=0 &
python3 main_incremental.py --exp_name design7_lwf_lr0005_bs32 --datasets birds --num_tasks 4 --network disentangle --disentangle_design design7 --heads_architecture design7 --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_birds_new/ --lr 0.005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach lwf --lamb 1 --T 2 --gpu=1 ;


'

:'
#pending, design 2 ewc
python3 main_incremental.py --exp_name design2_ewc5000_lr005_bs32 --datasets flowers --num_tasks 4 --network disentangle --disentangle_design design2 --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_flowers/ --lr 0.05 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach ewc --lamb 5000 --sampling_type max_pred --num_samples -1 --gpu=0 &
python3 main_incremental.py --exp_name design2_ewc5000_lr0005_bs32 --datasets flowers --num_tasks 4 --network disentangle --disentangle_design design2 --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_flowers/ --lr 0.005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach ewc --lamb 5000 --sampling_type max_pred --num_samples -1 --gpu=1 &
python3 main_incremental.py --exp_name design2_ewc5000_lr00005_bs32 --datasets flowers --num_tasks 4 --network disentangle --disentangle_design design2 --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_flowers/ --lr 0.0005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach ewc --lamb 5000 --sampling_type max_pred --num_samples -1 --gpu=2 ;
#pending design 6/7 ewc
python3 main_incremental.py --exp_name design6_ewc5000_lr0005_bs32 --datasets flowers --num_tasks 4 --network disentangle --disentangle_design design6 --heads_architecture design6 --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_flowers/ --lr 0.005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach ewc --lamb 5000 --sampling_type max_pred --num_samples -1 --gpu=0 &
python3 main_incremental.py --exp_name design6_ewc5000_lr00005_bs32 --datasets flowers --num_tasks 4 --network disentangle --disentangle_design design6 --heads_architecture design6 --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_flowers/ --lr 0.0005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach ewc --lamb 5000 --sampling_type max_pred --num_samples -1 --gpu=1 &
python3 main_incremental.py --exp_name design7_ewc5000_lr00005_bs32 --datasets flowers --num_tasks 4 --network disentangle --disentangle_design design7 --heads_architecture design7 --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_flowers/ --lr 0.0005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach ewc --lamb 5000 --sampling_type max_pred --num_samples -1 --gpu=2 ;
#pending lwf design 7
python3 main_incremental.py --exp_name design7_ewc5000_lr0005_bs32 --datasets flowers --num_tasks 4 --network disentangle --disentangle_design design7 --heads_architecture design7 --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_flowers/ --lr 0.005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach ewc --lamb 5000 --sampling_type max_pred --num_samples -1 --gpu=1 &
python3 main_incremental.py --exp_name design7_ewc5000_lr00005_bs32 --datasets flowers --num_tasks 4 --network disentangle --disentangle_design design7 --heads_architecture design7 --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_flowers/ --lr 0.0005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach ewc --lamb 5000 --sampling_type max_pred --num_samples -1 --gpu=2 ;


#birds design 1
python3 main_incremental.py --exp_name design1_finetune_lr005_bs32 --datasets birds --num_tasks 4 --network disentangle --disentangle_design design1 --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_birds/ --lr 0.05 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach finetune --gpu=0 &
python3 main_incremental.py --exp_name design1_finetune_lr0005_bs32 --datasets birds --num_tasks 4 --network disentangle --disentangle_design design1 --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_birds/ --lr 0.005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach finetune --gpu=1 &
python3 main_incremental.py --exp_name design1_finetune_lr00005_bs32 --datasets birds --num_tasks 4 --network disentangle --disentangle_design design1 --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_birds/ --lr 0.0005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach finetune --gpu=2 ;
#flowers design 1
python3 main_incremental.py --exp_name design1_finetune_lr005_bs32 --datasets flowers --num_tasks 4 --network disentangle --disentangle_design design1 --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_flowers/ --lr 0.05 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach finetune --gpu=0 &
python3 main_incremental.py --exp_name design1_finetune_lr0005_bs32 --datasets flowers --num_tasks 4 --network disentangle --disentangle_design design1 --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_flowers/ --lr 0.005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach finetune --gpu=1 &
python3 main_incremental.py --exp_name design1_finetune_lr00005_bs32 --datasets flowers --num_tasks 4 --network disentangle --disentangle_design design1 --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_flowers/ --lr 0.0005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach finetune --gpu=2 ;
#birds design 3
python3 main_incremental.py --exp_name design3_finetune_lr005_bs32 --datasets birds --num_tasks 4 --network disentangle --disentangle_design design3 --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_birds/ --lr 0.05 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach finetune --gpu=0 &
python3 main_incremental.py --exp_name design3_finetune_lr0005_bs32 --datasets birds --num_tasks 4 --network disentangle --disentangle_design design3 --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_birds/ --lr 0.005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach finetune --gpu=1 &
python3 main_incremental.py --exp_name design3_finetune_lr00005_bs32 --datasets birds --num_tasks 4 --network disentangle --disentangle_design design3 --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_birds/ --lr 0.0005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach finetune --gpu=2 ;
#flowers design 3
python3 main_incremental.py --exp_name design3_finetune_lr005_bs32 --datasets flowers --num_tasks 4 --network disentangle --disentangle_design design3 --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_flowers/ --lr 0.05 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach finetune --gpu=0 &
python3 main_incremental.py --exp_name design3_finetune_lr0005_bs32 --datasets flowers --num_tasks 4 --network disentangle --disentangle_design design3 --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_flowers/ --lr 0.005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach finetune --gpu=1 &
python3 main_incremental.py --exp_name design3_finetune_lr00005_bs32 --datasets flowers --num_tasks 4 --network disentangle --disentangle_design design3 --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_flowers/ --lr 0.0005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach finetune --gpu=2 ;
#birds design 5
python3 main_incremental.py --exp_name design5_finetune_lr005_bs32 --datasets birds --num_tasks 4 --network disentangle --disentangle_design design5 --heads_architecture design5 --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_birds/ --lr 0.05 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach finetune --gpu=0 &
python3 main_incremental.py --exp_name design5_finetune_lr0005_bs32 --datasets birds --num_tasks 4 --network disentangle --disentangle_design design5 --heads_architecture design5 --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_birds/ --lr 0.005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach finetune --gpu=1 &
python3 main_incremental.py --exp_name design5_finetune_lr00005_bs32 --datasets birds --num_tasks 4 --network disentangle --disentangle_design design5 --heads_architecture design5 --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_birds/ --lr 0.0005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach finetune --gpu=2 ;
#flowers design 5
python3 main_incremental.py --exp_name design5_finetune_lr005_bs32 --datasets flowers --num_tasks 4 --network disentangle --disentangle_design design5 --heads_architecture design5 --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_flowers/ --lr 0.05 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach finetune --gpu=0 &
python3 main_incremental.py --exp_name design5_finetune_lr0005_bs32 --datasets flowers --num_tasks 4 --network disentangle --disentangle_design design5 --heads_architecture design5 --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_flowers/ --lr 0.005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach finetune --gpu=1 &
python3 main_incremental.py --exp_name design5_finetune_lr00005_bs32 --datasets flowers --num_tasks 4 --network disentangle --disentangle_design design5 --heads_architecture design5 --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_flowers/ --lr 0.0005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach finetune --gpu=2;


python3 main_incremental.py --exp_name design7_ewc5000_lr0005_bs32 --datasets flowers --num_tasks 4 --network disentangle --disentangle_design design7 --heads_architecture design7 --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_flowers/ --lr 0.005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach ewc --lamb 5000 --sampling_type max_pred --num_samples -1 --gpu=3 ;
python3 main_incremental.py --exp_name design7_ewc5000_lr00005_bs32 --datasets flowers --num_tasks 4 --network disentangle --disentangle_design design7 --heads_architecture design7 --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_flowers/ --lr 0.0005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach ewc --lamb 5000 --sampling_type max_pred --num_samples -1 --gpu=3 ;

#pending 
python3 main_incremental.py --exp_name design7_lwf_lr0005_bs32 --datasets flowers --num_tasks 4 --network disentangle --disentangle_design design7 --heads_architecture design7 --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_flowers/ --lr 0.005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach lwf --lamb 1 --T 2 --gpu=0 &
python3 main_incremental.py --exp_name design7_lwf_lr00005_bs32 --datasets flowers --num_tasks 4 --network disentangle --disentangle_design design7 --heads_architecture design7 --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_flowers/ --lr 0.0005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach lwf --lamb 1 --T 2 --gpu=1 ;


#finetune nobn birds 4
python3 main_incremental.py --exp_name coloronly_nobn_new_finetune_lr005_bs32 --datasets birds --num_tasks 1 --network disentangle --disentangle_design coloronly --nepochs 200 --batch_size 32 --results_path data/experiments/1tasks_birds/ --lr 0.05 --lr_factor 3 --lr_patience 200 --lr_min 1e-16 --momentum 0.9 --weight_decay 0.0002 --approach finetune --use_bn 0 --gpu=0 &
python3 main_incremental.py --exp_name coloronly_nobn_new_finetune_lr0005_bs32 --datasets birds --num_tasks 1 --network disentangle --disentangle_design coloronly --nepochs 200 --batch_size 32 --results_path data/experiments/1tasks_birds/ --lr 0.005 --lr_factor 3 --lr_patience 200 --lr_min 1e-16 --momentum 0.9 --weight_decay 0.0002 --approach joint --use_bn 0 --gpu=1 &
python3 main_incremental.py --exp_name coloronly_nobn_new_finetune_lr00005_bs32 --datasets birds --num_tasks 1 --network disentangle --disentangle_design coloronly --nepochs 200 --batch_size 32 --results_path data/experiments/1tasks_birds/ --lr 0.0005 --lr_factor 3 --lr_patience 200 --lr_min 1e-16 --momentum 0.9 --weight_decay 0.0002 --approach joint --use_bn 0 --gpu=2 ;

#finetune nobn flowers 4
python3 main_incremental.py --exp_name coloronly_nobn_new_finetune_lr005_bs32 --datasets flowers --num_tasks 1 --network disentangle --disentangle_design coloronly --nepochs 200 --batch_size 32 --results_path data/experiments/1tasks_flowers/ --lr 0.05 --lr_factor 3 --lr_patience 200 --lr_min 1e-16 --momentum 0.9 --weight_decay 0.0002 --approach finetune --use_bn 0 --gpu=0 &
python3 main_incremental.py --exp_name coloronly_nobn_new_finetune_lr0005_bs32 --datasets flowers --num_tasks 1 --network disentangle --disentangle_design coloronly --nepochs 200 --batch_size 32 --results_path data/experiments/1tasks_flowers/ --lr 0.005 --lr_factor 3 --lr_patience 200 --lr_min 1e-16 --momentum 0.9 --weight_decay 0.0002 --approach finetune --use_bn 0 --gpu=1 &
python3 main_incremental.py --exp_name coloronly_nobn_new_finetune_lr00005_bs32 --datasets flowers --num_tasks 1 --network disentangle --disentangle_design coloronly --nepochs 200 --batch_size 32 --results_path data/experiments/1tasks_flowers/ --lr 0.0005 --lr_factor 3 --lr_patience 200 --lr_min 1e-16 --momentum 0.9 --weight_decay 0.0002 --approach finetune --use_bn 0 --gpu=2 ;




#birds design7bc
python3 main_incremental.py --exp_name design7b_finetune_lr005_bs32 --datasets birds --num_tasks 4 --network disentangle --disentangle_design design7 --heads_architecture design7b --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_birds/ --lr 0.05 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach finetune --gpu=3 &
python3 main_incremental.py --exp_name design7b_finetune_lr0005_bs32 --datasets birds --num_tasks 4 --network disentangle --disentangle_design design7 --heads_architecture design7b --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_birds/ --lr 0.005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach finetune --gpu=1 &
python3 main_incremental.py --exp_name design7b_finetune_lr00005_bs32 --datasets birds --num_tasks 4 --network disentangle --disentangle_design design7 --heads_architecture design7b --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_birds/ --lr 0.0005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach finetune --gpu=2 ;
python3 main_incremental.py --exp_name design7c_finetune_lr005_bs32 --datasets birds --num_tasks 4 --network disentangle --disentangle_design design7 --heads_architecture design7c --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_birds/ --lr 0.05 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach finetune --gpu=3 &
python3 main_incremental.py --exp_name design7c_finetune_lr0005_bs32 --datasets birds --num_tasks 4 --network disentangle --disentangle_design design7 --heads_architecture design7c --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_birds/ --lr 0.005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach finetune --gpu=1 &
python3 main_incremental.py --exp_name design7c_finetune_lr00005_bs32 --datasets birds --num_tasks 4 --network disentangle --disentangle_design design7 --heads_architecture design7c --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_birds/ --lr 0.0005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach finetune --gpu=2 ;



#birds design6bc
python3 main_incremental.py --exp_name design6b_finetune_lr005_bs32 --datasets birds --num_tasks 4 --network disentangle --disentangle_design design6 --heads_architecture design6b --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_birds/ --lr 0.05 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach finetune --gpu=3 &
python3 main_incremental.py --exp_name design6b_finetune_lr0005_bs32 --datasets birds --num_tasks 4 --network disentangle --disentangle_design design6 --heads_architecture design6b --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_birds/ --lr 0.005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach finetune --gpu=1 &
python3 main_incremental.py --exp_name design6b_finetune_lr00005_bs32 --datasets birds --num_tasks 4 --network disentangle --disentangle_design design6 --heads_architecture design6b --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_birds/ --lr 0.0005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach finetune --gpu=2 ;
python3 main_incremental.py --exp_name design6c_finetune_lr005_bs32 --datasets birds --num_tasks 4 --network disentangle --disentangle_design design6 --heads_architecture design6c --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_birds/ --lr 0.05 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach finetune --gpu=3 &
python3 main_incremental.py --exp_name design6c_finetune_lr0005_bs32 --datasets birds --num_tasks 4 --network disentangle --disentangle_design design6 --heads_architecture design6c --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_birds/ --lr 0.005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach finetune --gpu=1 &
python3 main_incremental.py --exp_name design6c_finetune_lr00005_bs32 --datasets birds --num_tasks 4 --network disentangle --disentangle_design design6 --heads_architecture design6c --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_birds/ --lr 0.0005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach finetune --gpu=2 ;



#flowers design7bc
python3 main_incremental.py --exp_name design7b_finetune_lr005_bs32 --datasets flowers --num_tasks 4 --network disentangle --disentangle_design design7 --heads_architecture design7b --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_birds/ --lr 0.05 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach finetune --gpu=3 &
python3 main_incremental.py --exp_name design7b_finetune_lr0005_bs32 --datasets flowers --num_tasks 4 --network disentangle --disentangle_design design7 --heads_architecture design7b --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_birds/ --lr 0.005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach finetune --gpu=1 &
python3 main_incremental.py --exp_name design7b_finetune_lr00005_bs32 --datasets flowers --num_tasks 4 --network disentangle --disentangle_design design7 --heads_architecture design7b --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_birds/ --lr 0.0005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach finetune --gpu=2 ;
python3 main_incremental.py --exp_name design7c_finetune_lr005_bs32 --datasets flowers --num_tasks 4 --network disentangle --disentangle_design design7 --heads_architecture design7c --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_birds/ --lr 0.05 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach finetune --gpu=3 &
python3 main_incremental.py --exp_name design7c_finetune_lr0005_bs32 --datasets flowers --num_tasks 4 --network disentangle --disentangle_design design7 --heads_architecture design7c --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_birds/ --lr 0.005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach finetune --gpu=1 &
python3 main_incremental.py --exp_name design7c_finetune_lr00005_bs32 --datasets flowers --num_tasks 4 --network disentangle --disentangle_design design7 --heads_architecture design7c --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_birds/ --lr 0.0005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach finetune --gpu=2 ;


#flowers design6bc
python3 main_incremental.py --exp_name design6b_finetune_lr005_bs32 --datasets flowers --num_tasks 4 --network disentangle --disentangle_design design6 --heads_architecture design6b --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_birds/ --lr 0.05 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach finetune --gpu=3 &
python3 main_incremental.py --exp_name design6b_finetune_lr0005_bs32 --datasets flowers --num_tasks 4 --network disentangle --disentangle_design design6 --heads_architecture design6b --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_birds/ --lr 0.005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach finetune --gpu=1 &
python3 main_incremental.py --exp_name design6b_finetune_lr00005_bs32 --datasets flowers --num_tasks 4 --network disentangle --disentangle_design design6 --heads_architecture design6b --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_birds/ --lr 0.0005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach finetune --gpu=2 ;
python3 main_incremental.py --exp_name design6c_finetune_lr005_bs32 --datasets flowers --num_tasks 4 --network disentangle --disentangle_design design6 --heads_architecture design6c --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_birds/ --lr 0.05 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach finetune --gpu=3 &
python3 main_incremental.py --exp_name design6c_finetune_lr0005_bs32 --datasets flowers --num_tasks 4 --network disentangle --disentangle_design design6 --heads_architecture design6c --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_birds/ --lr 0.005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach finetune --gpu=1 &
python3 main_incremental.py --exp_name design6c_finetune_lr00005_bs32 --datasets flowers --num_tasks 4 --network disentangle --disentangle_design design6 --heads_architecture design6c --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_birds/ --lr 0.0005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach finetune --gpu=2 ;
'


python3 main_incremental.py --exp_name design7b_lwf_lr005_bs32 --datasets flowers --num_tasks 4 --network disentangle --disentangle_design design7 --heads_architecture design7b --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_flowers/ --lr 0.05 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach lwf --lamb 1 --T 2 --gpu=0 &
python3 main_incremental.py --exp_name design7b_lwf_lr0005_bs32 --datasets flowers --num_tasks 4 --network disentangle --disentangle_design design7 --heads_architecture design7b --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_flowers/ --lr 0.005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach lwf --lamb 1 --T 2 --gpu=1 ;
python3 main_incremental.py --exp_name design7b_lwf_lr00005_bs32 --datasets flowers --num_tasks 4 --network disentangle --disentangle_design design7 --heads_architecture design7b --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_flowers/ --lr 0.0005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach lwf --lamb 1 --T 2 --gpu=0 &
python3 main_incremental.py --exp_name design7_ewc5000_lr005_bs32 --datasets flowers --num_tasks 4 --network disentangle --disentangle_design design7 --heads_architecture design7b --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_flowers/ --lr 0.05 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach ewc --lamb 5000 --sampling_type max_pred --num_samples -1 --gpu=1 ;
python3 main_incremental.py --exp_name design7_ewc5000_lr0005_bs32 --datasets flowers --num_tasks 4 --network disentangle --disentangle_design design7 --heads_architecture design7b --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_flowers/ --lr 0.005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach ewc --lamb 5000 --sampling_type max_pred --num_samples -1 --gpu=0 &
python3 main_incremental.py --exp_name design7_ewc5000_lr00005_bs32 --datasets flowers --num_tasks 4 --network disentangle --disentangle_design design7 --heads_architecture design7b --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_flowers/ --lr 0.0005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach ewc --lamb 5000 --sampling_type max_pred --num_samples -1 --gpu=1 ;


python3 main_incremental.py --exp_name design7b_lwf_lr005_bs32 --datasets birds --num_tasks 4 --network disentangle --disentangle_design design7 --heads_architecture design7b --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_birds/ --lr 0.05 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach lwf --lamb 1 --T 2 --gpu=0 &
python3 main_incremental.py --exp_name design7b_lwf_lr0005_bs32 --datasets birds --num_tasks 4 --network disentangle --disentangle_design design7 --heads_architecture design7b --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_birds/ --lr 0.005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach lwf --lamb 1 --T 2 --gpu=1 ;
python3 main_incremental.py --exp_name design7b_lwf_lr00005_bs32 --datasets birds --num_tasks 4 --network disentangle --disentangle_design design7 --heads_architecture design7b --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_birds/ --lr 0.0005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach lwf --lamb 1 --T 2 --gpu=0 &
python3 main_incremental.py --exp_name design7_ewc5000_lr005_bs32 --datasets birds --num_tasks 4 --network disentangle --disentangle_design design7 --heads_architecture design7b --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_birds/ --lr 0.05 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach ewc --lamb 5000 --sampling_type max_pred --num_samples -1 --gpu=1 ;
python3 main_incremental.py --exp_name design7_ewc5000_lr0005_bs32 --datasets birds --num_tasks 4 --network disentangle --disentangle_design design7 --heads_architecture design7b --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_birds/ --lr 0.005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach ewc --lamb 5000 --sampling_type max_pred --num_samples -1 --gpu=0 &
python3 main_incremental.py --exp_name design7_ewc5000_lr00005_bs32 --datasets birds --num_tasks 4 --network disentangle --disentangle_design design7 --heads_architecture design7b --nepochs 200 --batch_size 32 --results_path data/experiments/4tasks_birds/ --lr 0.0005 --lr_factor 3 --lr_patience 15 --lr_min 1e-6 --momentum 0.9 --weight_decay 0.0002 --approach ewc --lamb 5000 --sampling_type max_pred --num_samples -1 --gpu=1 ;


